// scripts/inline-canon.ts
// Run: bun run scripts/inline-canon.ts <path-to-canon.png>
import { readFileSync, writeFileSync } from 'fs';

const src = process.argv[2];
if (!src) { console.error('usage: inline-canon.ts <canon.png>'); process.exit(1); }
const bytes = readFileSync(src);

// Detect MIME from magic bytes — the file extension can lie.
let mime: string;
if (bytes.length >= 4 && bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4e && bytes[3] === 0x47) {
  mime = 'image/png';
} else if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) {
  mime = 'image/jpeg';
} else {
  console.error(`error: unrecognized image format in ${src} (not PNG or JPEG)`);
  process.exit(1);
}

const b64 = bytes.toString('base64');
const out = `// AUTO-GENERATED by scripts/inline-canon.ts — do not edit by hand.
export const CANON_IMAGE_DATA_URL =
  "data:${mime};base64,${b64}";
`;
writeFileSync('supabase/functions/_shared/assets/canon-b64.ts', out);
console.log(`Wrote canon-b64.ts (${mime}, ${b64.length} base64 chars)`);
