// scripts/inline-canon.ts
// Run: bun run scripts/inline-canon.ts <path-to-canon.png>
import { readFileSync, writeFileSync } from 'fs';

const src = process.argv[2];
if (!src) { console.error('usage: inline-canon.ts <canon.png>'); process.exit(1); }
const b64 = readFileSync(src).toString('base64');
const out = `// AUTO-GENERATED by scripts/inline-canon.ts — do not edit by hand.
export const CANON_IMAGE_DATA_URL =
  "data:image/png;base64,${b64}";
`;
writeFileSync('supabase/functions/_shared/assets/canon-b64.ts', out);
console.log(`Wrote canon-b64.ts (${b64.length} base64 chars)`);
